### ISSUE TITLE
What is the difference between "net.set_weights(opt)" and "__setstate__" ??

### ISSUE THREAD

**Issue by EomAA** [sebastkm/hybrid-fem-nn#5]
Hi, 

I am trying to understand your codes and implementation on this hybrid FE-NN work.
This is a great work, thanks!

Actually, I am new to Python as well as NN... even FEniCS..

I have a question as follows.

**Question 1**
Let's say I want to input the arbitrary weights values into the network.
In this situation, is it right way to actually save and load data including weights through "pickle" as coded in the "test_save_and_load" function in "test_basics.py"? or is it the best way to just use the "set_weights" function?

**Question 2**
If the use of the "set_weights" is the best way,
I am also wondering after calling "set_weights" if the weights will be assigned to the network, and then can I use this network for the next additional processes.

Thank you in advance for your help.

Best,

**Comment by sebastkm** [comment]
Hi,

I'm not entirely sure if I understand what you mean by "input the arbitrary weights values into the network".
Do you already have some weights you want to use for the network?

If so, then I would recommend using `set_weights` unless you have saved the weights to a file with the `save` function of the `ANN` class.
With `set_weights` the ANN object is assigned the given weights and you can use it as normal, yes.
However, I recommend disabling tape annotation while setting weights:
```
with stop_annotating():
   net.set_weights(new_weights)
```
This is to avoid computing the gradients of this assignment during backpropagation.

Note that the format used for the `new_weights` is the same as given by `net.﻿﻿weights_flat`. That is, a flat list of `Constant` objects representing the different weights/biases.
